name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # 1. REQUIRED PERMISSIONS
    permissions:
      actions: write
      issues: write
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install and Test
        # We tell GitHub to run these inside the 'backend' folder
        working-directory: ./backend 
        run: |
          npm install
          npm test

      # 2. THE REPLAY STEP
      # This step stays the same, it doesn't need to be in the backend folder
      - name: PR Build Replay
        if: failure()
        uses: nirjxr26/BlameLess@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-retries: '1'
